export const GET_LIST_POST_USER_REQUESTING = 'GET_LIST_POST_USER_REQUESTING';
export const GET_LIST_POST_USER_ERROR = 'GET_LIST_POST_USER_ERROR';
export const GET_LIST_POST_USER_SUCCESS = 'GET_LIST_POST_USER_SUCCESS';
