export const GET_LIST_COMMENT_POST_REQUESTING = 'GET_LIST_COMMENT_POST_REQUESTING';
export const GET_LIST_COMMENT_POST_SUCCESS = 'GET_LIST_COMMENT_POST_SUCCESS';
export const GET_LIST_COMMENT_POST_ERROR = 'GET_LIST_COMMENT_POST_ERROR';
